version: "3"

dotenv: ["../../../.env"]

tasks:
  # install scripts
  install-frontend:
    desc: install frontend dependencies
    dir: ./frontend
    cmds:
      - bun install --verbose

  install-tenapp:
    desc: install tenapp dependencies
    dir: ./tenapp
    cmds:
      - tman install

  install-tenapp-python-deps:
    desc: install tenapp python dependencies
    deps: [install-tenapp]
    dir: ./tenapp
    cmds:
      - python scripts/install_python_deps.py

  build-api-server:
    desc: build api server
    dir: ../../../server
    cmds:
      - cmd: go mod tidy && go mod download && go build -o bin/api main.go
        platforms: [linux, darwin]
      - cmd: go mod tidy && go mod download && go build -o bin/api.exe main.go
        platforms: [windows]

  install:
    desc: install dependencies
    dir: ./tenapp
    cmds:
      - task: install-tenapp
      - task: install-tenapp-python-deps
      - task: install-frontend
      - task: build-api-server

  # run scripts
  run-tenapp:
    desc: run tenapp
    dir: ./tenapp
    cmds:
      - tman run start

  run-gd-server:
    desc: run tman dev http server for TMAN Designer
    dir: ./tenapp
    cmds:
      - tman designer

  run-frontend:
    desc: run frontend
    dir: ./frontend
    cmds:
      - bun run dev

  run-api-server:
    desc: run api server
    dir: ../../../server
    cmds:
      - cmd: ./bin/api -tenapp_dir={{.PWD}}/tenapp
        platforms: [linux, darwin]
      - cmd: powershell -Command "./bin/api.exe -tenapp_dir='{{.TASKFILE_DIR}}/tenapp'"
        platforms: [windows]

  run:
    desc: run everything
    deps:
      - task: run-gd-server
      - task: run-frontend
      - task: run-api-server

  # release scripts
  release:
    desc: release
    cmds:
      - cmd: ../../scripts/release.sh {{.PWD}}/tenapp
        platforms: [linux, darwin]
      - cmd: powershell -File "../../scripts/release.ps1" -tenappDir {{.PWD}}\tenapp
        platforms: [windows]
